/**********************************/
/* テーブル名: ユーザ情報                                 */
/**********************************/
CREATE TABLE TL_USERS(
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0),
  user_login VARCHAR(30) NOT NULL,
  user_password VARCHAR(30) NOT NULL,
  user_display_name VARCHAR(20),
  user_email VARCHAR(255),
  user_registerd DATE NOT NULL,
  PRIMARY KEY (user_id)
);

ALTER TABLE TL_USERS ADD CONSTRAINT tl_users_idx1 UNIQUE (user_login);