CREATE TABLE tl_users (
  ID BIGINT generated by default as identity (start with 0),
  user_id VARCHAR(30) NOT NULL,
  user_first_name VARCHAR(16),
  user_last_name VARCHAR(16),
  user_password VARCHAR(30) NOT NULL,
  user_email VARCHAR(255),
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX tl_users_idx1 on tl_users (user_id);